
version: '3.1'


services:
  # anylistapp:
  #   depends_on:
  #     - db
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   image: anylist-docker
  #   container_name: AnyListApp
  #   restart: always # reiniciar el contenedor si se detiene
  #   ports:
  #     - "${PORT}:${PORT}"
  #   environment:
  #     PORT: ${PORT}
  #   volumes:
  #     - ./:/usr/app
  db:
    image: postgres:14.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: anylistDB
    volumes:
      - ./postgres:/var/lib/postgresql/data